00. Pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [131]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


In [132]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found



## Introduction to tensors
### way represent data(mostly multidimensional)

###Creating tensors

PyTorch tensors are created using `torch.tensor()` more at-https://pytorch.org/docs/stable/tensors.html

In [133]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [134]:
#scalar(0) doesnt work like matrices or vectors

##### many dimensions of scalar are there...to find out what dimension in scalar tensor: run `scalar.ndim`

In [135]:
scalar.ndim

0

###### get tensor back as py int use `item()`

In [136]:
scalar.item()

7

In [137]:
scalar.shape

torch.Size([])

##### vector has 2 values...Dimension and Shape

In [138]:
#vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [139]:
vector[1]

tensor(4)

##### many dimensions of scalar are there...to find out what dimension in vector tensor: run `vector.ndim`

In [140]:
vector.ndim

1

In [141]:
vector.shape

torch.Size([2])

In [142]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [143]:
MATRIX[0]

tensor([7, 8])

In [144]:
MATRIX.ndim

2

In [145]:
MATRIX.shape

torch.Size([2, 2])

In [146]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [147]:
TENSOR.ndim

3

In [148]:
TENSOR.shape

torch.Size([1, 3, 3])

In [149]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [150]:
#PRACTICE TENSORS 1
tensor1 = torch.tensor([1])
print(tensor1.ndim)
print(tensor1.shape)
print(tensor1[0])
tensor1


1
torch.Size([1])
tensor(1)


tensor([1])

In [151]:
#PRACTICE TENSORS 2
#tensor2 = torch.tensor([1],[2],[3])
#TypeError: tensor() takes 1 positional argument but 3 were given
#WE HAVE TO MAKE IT LIKE A 2D TENSOR OR WE CAN ADD INSIDE THE SINGLES WHICH WILL REMAIN A 1D TENSOR
tensor2 = torch.tensor([1,2,3,4,55,52,54,5,353])
print(tensor2.ndim)
print(tensor2.shape)
print(tensor2[4])
tensor2


1
torch.Size([9])
tensor(55)


tensor([  1,   2,   3,   4,  55,  52,  54,   5, 353])

In [152]:
#PRACTICE TENSORS 3
#The below code doesnt work cuz:
#ValueError: expected sequence of length 2 at dim 1 (got 3)
#tensor3 = torch.tensor([[1,2],
#                        [1,2,3],
#                        [4]])
tensor3 = torch.tensor([[1,2,3],
                        [11,12,13],
                        [4,5,6]])
print(tensor3.ndim)
print(tensor3.shape)
print(tensor3[2])
print(tensor3[1,2])
tensor3


2
torch.Size([3, 3])
tensor([4, 5, 6])
tensor(13)


tensor([[ 1,  2,  3],
        [11, 12, 13],
        [ 4,  5,  6]])

In [153]:
#PRACTICE TENSORS 4

tensor4 = torch.tensor([[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]])
print(tensor4.ndim)
print(tensor4.shape)
print(tensor4[2])
print(tensor4[1,2])
tensor4


2
torch.Size([4, 5])
tensor([44,  5,  6, 10,  5])
tensor(13)


tensor([[ 1,  2,  3,  4, 65],
        [11, 12, 13, 89, 56],
        [44,  5,  6, 10,  5],
        [ 1,  2,  3, 46,  6]])

In [154]:
#PRACTICE TENSORS 5

tensor5 = torch.tensor([[[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]]])
print(tensor5.ndim)
print(tensor5.shape)

#print(tensor5[2]) not possible cuz:
#IndexError: index 2 is out of bounds for dimension 0 with size SOOO....:
print(tensor5[0,1])

#print(tensor5[1,2]) not possible cuz:
#index 1 is out of bounds for dimension 0 with size 1 SOOOO....:
print(tensor5[0,2,3])

tensor5


3
torch.Size([1, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(10)


tensor([[[ 1,  2,  3,  4, 65],
         [11, 12, 13, 89, 56],
         [44,  5,  6, 10,  5],
         [ 1,  2,  3, 46,  6]]])

In [155]:
#PRACTICE TENSORS 6

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65]
#                        [11,12,13,89,56],[12,22,32,42]
#                        [44,5,6,10,5],[22,33,44,55,66]
#                        [1,2,3,46,6],[23,33,43,53]]])
#CUZ:   TypeError must be lists, not tuples, were missing commas and first are 5 while seconds were 4 ,have to be equal....SOOO..:

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65,11],
#                        [11,12,13,89,56],[12,22,32,42,22],
#                        [44,5,6,10,5],[22,33,44,55,200],
#                        [1,2,3,46,6],[23,33,43,53,100]]])
#works....but same as before with size[1,8,5]....

tensor6 = torch.tensor([
                        [[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]],

                          [[32,43,54,65,11],
                          [12,22,32,42,22],
                          [22,33,44,55,200],
                          [23,33,43,53,100]]
                        ])

print(tensor6.ndim)
print(tensor6.shape)

print(tensor6[0,1])

print(tensor6[1,2,3])

tensor6


3
torch.Size([2, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(55)


tensor([[[  1,   2,   3,   4,  65],
         [ 11,  12,  13,  89,  56],
         [ 44,   5,   6,  10,   5],
         [  1,   2,   3,  46,   6]],

        [[ 32,  43,  54,  65,  11],
         [ 12,  22,  32,  42,  22],
         [ 22,  33,  44,  55, 200],
         [ 23,  33,  43,  53, 100]]])

**END OF PRACTICE**

##**RANDOM tensors**
Why random tensors?

it starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with RND nums -> look at data ->update RND nums -> look at data -> update RND nums

More at: https://pytorch.org/docs/stable/generated/torch.rand.html

In [156]:
#Create a random tensor of size (3,4)
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.2091, 0.4759, 0.5611, 0.5189],
        [0.3021, 0.4800, 0.7388, 0.7453],
        [0.8736, 0.0719, 0.9030, 0.3933]])

In [157]:
rand_tensor.ndim

2

In [158]:
#Create a random tensor of size (2,4,5)
rand_tensor2 = torch.rand(2,4,5)
rand_tensor2

tensor([[[0.7946, 0.8880, 0.1040, 0.8842, 0.5575],
         [0.9905, 0.8869, 0.5008, 0.4708, 0.9255],
         [0.1774, 0.4198, 0.5070, 0.6238, 0.6206],
         [0.0955, 0.6834, 0.7104, 0.0186, 0.9882]],

        [[0.1895, 0.3793, 0.6740, 0.5837, 0.6415],
         [0.2318, 0.0163, 0.3342, 0.8685, 0.0595],
         [0.2624, 0.6676, 0.8022, 0.8652, 0.6989],
         [0.8953, 0.7005, 0.8909, 0.2521, 0.1839]]])

In [159]:
rand_tensor2.ndim

3

In [160]:
rand_tensor2 = torch.rand(2,3,4,5)
print(rand_tensor2.shape)
print(rand_tensor2.ndim)
rand_tensor2

torch.Size([2, 3, 4, 5])
4


tensor([[[[0.2460, 0.6457, 0.7725, 0.8620, 0.0485],
          [0.4384, 0.9597, 0.3692, 0.6472, 0.2792],
          [0.5096, 0.9936, 0.9863, 0.4414, 0.8825],
          [0.3426, 0.1724, 0.4869, 0.4389, 0.0707]],

         [[0.1970, 0.5996, 0.2733, 0.6334, 0.4908],
          [0.3021, 0.7284, 0.7220, 0.1579, 0.7417],
          [0.9024, 0.2733, 0.7454, 0.3728, 0.9080],
          [0.7653, 0.4017, 0.7946, 0.6887, 0.0701]],

         [[0.0197, 0.9375, 0.1320, 0.4710, 0.6343],
          [0.6827, 0.2858, 0.0293, 0.9341, 0.7430],
          [0.5024, 0.1492, 0.2672, 0.4270, 0.8703],
          [0.1499, 0.2653, 0.7920, 0.4867, 0.1149]]],


        [[[0.4174, 0.2366, 0.2309, 0.9071, 0.8062],
          [0.3866, 0.2045, 0.8250, 0.3754, 0.3516],
          [0.2746, 0.0357, 0.5081, 0.3607, 0.0141],
          [0.6983, 0.9387, 0.0165, 0.3365, 0.5864]],

         [[0.2731, 0.1336, 0.1433, 0.7176, 0.8599],
          [0.7771, 0.5900, 0.9647, 0.2359, 0.4064],
          [0.4553, 0.9702, 0.6144, 0.2327, 0.7075],
  

In [161]:
#Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(3,224,224)) #height,width,color channels(rgb)
random_img_size_tensor.shape,random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [162]:
#PRACTiCE:
rand_tensorrr = torch.rand(1,1,1,1,1,1,1)
print(rand_tensorrr.shape)
print(rand_tensorrr.ndim)
print(rand_tensorrr)

rand_tensorr = torch.rand(1,2,3,4)
print(rand_tensorr.shape)
print(rand_tensorr.ndim)
print(rand_tensorr)

rand_tensor3 = torch.rand(2,3,4,5)
print(rand_tensor3.shape)
print(rand_tensor3.ndim)
print(rand_tensor3)

rand_tensor5 = torch.rand(3,2,3,2,6)
print(rand_tensor5.shape)
print(rand_tensor5.ndim)
rand_tensor5

torch.Size([1, 1, 1, 1, 1, 1, 1])
7
tensor([[[[[[[0.2249]]]]]]])
torch.Size([1, 2, 3, 4])
4
tensor([[[[0.0145, 0.0754, 0.1355, 0.3163],
          [0.3263, 0.0798, 0.6881, 0.3717],
          [0.5530, 0.3887, 0.2887, 0.9540]],

         [[0.5138, 0.3908, 0.6198, 0.6655],
          [0.9734, 0.8112, 0.2390, 0.0258],
          [0.8559, 0.2492, 0.6582, 0.4450]]]])
torch.Size([2, 3, 4, 5])
4
tensor([[[[9.1095e-01, 9.4944e-01, 8.6185e-01, 9.9683e-01, 2.8826e-01],
          [4.1519e-01, 7.9340e-01, 5.2971e-01, 7.0190e-01, 6.3986e-01],
          [2.5422e-01, 6.3990e-02, 7.8166e-01, 6.6436e-01, 9.5037e-02],
          [9.0077e-01, 5.9907e-01, 9.0140e-01, 2.2215e-01, 9.4209e-01]],

         [[5.1314e-01, 9.0616e-01, 1.0147e-01, 2.1708e-01, 7.6254e-01],
          [4.6427e-01, 5.3235e-01, 7.2724e-04, 8.2000e-01, 2.9255e-01],
          [4.9475e-01, 9.0935e-01, 7.0425e-01, 8.0184e-01, 9.0909e-01],
          [2.4915e-01, 6.8150e-01, 3.4604e-01, 3.9980e-01, 5.2464e-01]],

         [[4.4432e-01, 4.4017e-0

tensor([[[[[8.3466e-01, 2.4887e-01, 5.6401e-01, 7.7355e-01, 4.0544e-01,
            4.4250e-01],
           [9.4631e-01, 4.3930e-01, 2.4113e-01, 3.2702e-01, 5.1838e-01,
            7.4052e-01]],

          [[4.2793e-02, 5.7594e-01, 2.2006e-01, 1.7349e-01, 8.9912e-01,
            4.2970e-01],
           [7.3879e-01, 7.3989e-01, 2.2395e-01, 8.6991e-01, 5.4372e-01,
            5.6072e-01]],

          [[3.8138e-01, 4.2543e-01, 8.2390e-02, 3.5997e-01, 4.7988e-01,
            9.7197e-01],
           [5.9054e-01, 4.2530e-01, 2.0254e-01, 5.6478e-01, 3.1753e-01,
            1.1692e-01]]],


         [[[4.0551e-02, 7.4169e-01, 9.0813e-01, 2.1294e-01, 1.8730e-01,
            4.5096e-01],
           [9.3081e-01, 6.1065e-01, 5.2057e-01, 9.0410e-01, 9.4079e-01,
            7.7709e-01]],

          [[8.7065e-02, 9.8775e-01, 9.0863e-01, 2.0102e-01, 2.4084e-01,
            2.5353e-01],
           [8.0893e-01, 7.9738e-01, 8.7255e-01, 7.9087e-01, 5.4272e-01,
            5.7754e-01]],

          [[7.7730

###Zeros and ones

In [163]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [164]:
zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [165]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [166]:
ones.dtype

torch.float32

In [167]:
ones*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [168]:
# Use torch.range()
one_to_ten = torch.arange(0,1000,78)
one_to_ten

tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])

In [169]:
# Tensor like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [170]:
two_to_ten_like = torch.ones_like(input=one_to_ten)
two_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Data Type

**Note:** Tensor data types is one of the 3 big errors you may run into with PyTorch & deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

  Learn more about precision incomputing here:
  https://en.wikipedia.org/wiki/Precision_(computer_science)

In [171]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what datatype is the tensor(e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [172]:
float_32_tensor.dtype

torch.float32

In [173]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [174]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [175]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [176]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [177]:
int_long_tensor = torch.tensor([3,6,9], dtype= torch.long)
int_long_tensor

tensor([3, 6, 9])

In [178]:
float_32_tensor * int_long_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

  1. Tensors not right datatype - to do get datatype from a tensor,can use `tensor.type`
  2. Tensors not right shape - to get shape from a tensor use `tensor.shape`
  3. Tensors not on the right device - to get device from tensor use `tensor.device`

In [179]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1522, 0.1184, 0.0881, 0.1113],
        [0.5086, 0.1380, 0.1131, 0.9411],
        [0.4496, 0.3693, 0.9301, 0.1307]])

In [180]:
# Find details of Tensor

print(some_tensor)
print("Datatype of tensor: "+str(some_tensor.dtype))
print(f"Shape of tensor {some_tensor.shape}")
print(f"Device tensor is {some_tensor.device}")

tensor([[0.1522, 0.1184, 0.0881, 0.1113],
        [0.5086, 0.1380, 0.1131, 0.9411],
        [0.4496, 0.3693, 0.9301, 0.1307]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu


In [181]:
# Practice
some_tensor2 = torch.rand(3,4)
print(some_tensor2)
print("Datatype of tensor: "+str(some_tensor2.dtype))
print(f"Shape of tensor {some_tensor2.shape}")
print(f"Device tensor is {some_tensor2.device}")

some_tensor3 = torch.rand(3,4)
print(some_tensor3)
print("Datatype of tensor: "+str(some_tensor3.dtype))
print(f"Shape of tensor {some_tensor3.shape}")
print(f"Device tensor is {some_tensor3.device}")

tensor([[0.1585, 0.5703, 0.8073, 0.9089],
        [0.0865, 0.6299, 0.1278, 0.4212],
        [0.2337, 0.2509, 0.0832, 0.0604]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu
tensor([[0.8401, 0.3304, 0.1607, 0.9970],
        [0.3839, 0.8783, 0.6683, 0.7641],
        [0.2109, 0.5728, 0.8374, 0.4885]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu


### Manipulating tensors (tensor operations)

Tensor operations include
* Addition
* Substraction
* Multiplications (elementwise)
* Division
* Matrix multiplication

In [182]:
# Create a tensor
tensor = torch.tensor([1,2,3])

#addition
tensor+10

tensor([11, 12, 13])

In [183]:
#multiply (elementwise)
tensor*10

tensor([10, 20, 30])

In [184]:
#Try out PyTorch in-built funstions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [185]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [186]:
tensor%3

tensor([1, 2, 0])

## Matrix Multiplication

Two main ways of performing multiplication in DL:

1. Elementwise
2. Matrix Multiplication (dot product)
In PyTorch we use `torch.matmul(tensor_1,tensor_2)` or **tensor1@tensor2** or `torch.mm(tensor_1,tensor_2)`

Here can be found more: https://www.mathisfun.com/algebra/matrix-multiplying.html

### Two of the most important rules in matrix mult are:

1. The **inner dimensions must match**


*   (3,2) @ (3,2) won't work || matmul(torch.rand(3,2),torch.rand(3,2))
*   (2,3) @ (3,2) will work || matmul(torch.rand(2,3),torch.rand(3,2))
*   (3,2) @ (2,3) will work || matmul(torch.rand(3,2),torch.rand(2,3))



In [187]:
# Element wise Multiplication
print(tensor,"*",tensor)
print("Equals",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [188]:
# Matrix Multiplication

print(tensor,".",tensor)
print("Equals ",torch.matmul(tensor,tensor))

tensor([1, 2, 3]) . tensor([1, 2, 3])
Equals  tensor(14)


In [189]:
# Matrix Multiplication by hand

1*1 + 2*2 + 3*3

14

In [190]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.62 ms, sys: 926 µs, total: 2.55 ms
Wall time: 3.87 ms


In [191]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.3 ms, sys: 19 µs, total: 1.32 ms
Wall time: 1.19 ms


tensor(14)

### One of the most common errors in DL: `Shape Errors`

In [192]:
# Shape for a matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A,tensor_B)

To fix shapes:
we can manipulate the shape of a matrix by transposing it.

A `transpose` switches the axes or dims of a given sensor

syntax: `matrix_A.T`

In [193]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [194]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [195]:
torch.mm(tensor_A,tensor_B.T),torch.mm(tensor_A,tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

##Finding the min,max,mean,sum,etc (tensor aggregation)

In [196]:
#Create a tensor
x= torch.arange(1,100,10)
x,x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [197]:
#Find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [198]:
#Find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [199]:
# Find the mean - note: torch.mean requires a tensor of float32 dtype to work, .arange is Long type
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [200]:
# Find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## Find the positional min and max

In [201]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [202]:
#Find the position in tensor tha has the minimum value with `argmin()` -> returns index
x.argmin()

tensor(0)

In [203]:
#Find the position in tensor tha has the minimum value with `argmin()` -> returns index
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other (vstack) or side by side (`hstack`)

* Squeeze - removes all `1` dimensions from a tensor

* Unsqueeze - add a `1` dimension to a target tensor

* Permute - Return a view of the input with dims permuted(swapped) in a certain way

In [204]:
# Create a tensor
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [205]:
# Add an extra dimension
x_reshaped1 = x.reshape(1,9)
x_reshaped1, x_reshaped1.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [206]:
x_reshaped2 = x.reshape(9,1)
x_reshaped2,x_reshaped2.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [207]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [208]:
# Changing z changes x (because a view of a tensor shares the same memory )
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [209]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [210]:
#torch.squeeze() - removes all single dims from target tensor
print(f"Porevious tensor: {x_reshaped1}")
print(f"Previous shape: {x_reshaped1.shape}")

#Remove extra dim from x_reshaped1
x_squeezed = x_reshaped1.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Porevious tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [211]:
#torch.unsqueeze(). - adds a single dim to a target tensor
print(f"Porevious tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Remove extra dim from x_reshaped1
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Porevious tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [212]:
x_reshaped1.squeeze().shape

torch.Size([9])

In [213]:
# torch.permute - rearranges the dimension of a target tensor in a specified order
x_original = torch.rand(size = (224,224,3)) # [height,width,color_channels]

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Prev shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Prev shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [214]:
x_original[0,0,0]

tensor(0.2295)

In [215]:
x_original[0,0,0] = 69
x_original[0,0,0]

tensor(69.)

In [216]:
x_permuted[0,0,0] # same cuz shares the same memory

tensor(69.)

## Indexing (selecting data from tensors)

Indexing in pytorch is similar to numpy indexing

In [217]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [218]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [219]:
# Let's index on the middle bracket (dim=1)
print(x[0][0])
print(x[0][1])

tensor([1, 2, 3])
tensor([4, 5, 6])


In [220]:
 # Let's index on the most inner bracket (last dim)

print(x[0][0][0])
print(x[0][1][2])
print(x[0,2,2])

tensor(1)
tensor(6)
tensor(9)


In [221]:
# We can also use ":" to select all of a target dim

print(x[:,0])
print(x[:,2])

tensor([[1, 2, 3]])
tensor([[7, 8, 9]])


In [222]:
# Get all values of 0th and 1st dims but only index of 1 aof 2ns dim

x[:,:,1]

tensor([[2, 5, 8]])

In [223]:
# Get all values of 0 dim but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [224]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [225]:
# Index on x to return 9
print(x[0,0,2])

# Index on x to return 3,6,9
x[:,:,2]

tensor(3)


tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical library.

And cuz of this, PyTorch has functionality to interact with it.

  * Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
  * PyTorch tensor -> NumPy -> `torch.tensor.numpy()`

In [226]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise like `.type(specified_type)`
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [227]:
array.dtype, torch.arange(1.0,8.0).dtype

(dtype('float64'), torch.float32)

In [228]:
# Changing the value of array wont change the tensor
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [233]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [234]:
numpy_tensor.dtype,tensor.dtype

(dtype('float32'), torch.float32)

In [235]:
# Changing the tensor wont change the numpytensor
tensor = tensor +1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [231]:
# No, tensor += 1 and tensor = tensor + 1 are not exactly the same in PyTorch, even though they may seem similar at first glance.