<a href="https://colab.research.google.com/github/nnfuad/pytorch00/blob/main/00_pytorch_fund_vid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [35]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


In [36]:
!nvidia-smi

Sun Aug 18 15:42:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--


## Introduction to tensors
### way represent data(mostly multidimensional)

###Creating tensors

PyTorch tensors are created using `torch.tensor()` more at-https://pytorch.org/docs/stable/tensors.html

In [37]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [38]:
#scalar(0) doesnt work like matrices or vectors

##### many dimensions of scalar are there...to find out what dimension in scalar tensor: run `scalar.ndim`

In [39]:
scalar.ndim

0

###### get tensor back as py int use `item()`

In [40]:
scalar.item()

7

In [41]:
scalar.shape

torch.Size([])

##### vector has 2 values...Dimension and Shape

In [42]:
#vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [43]:
vector[1]

tensor(4)

##### many dimensions of scalar are there...to find out what dimension in vector tensor: run `vector.ndim`

In [44]:
vector.ndim

1

In [45]:
vector.shape

torch.Size([2])

In [46]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [47]:
MATRIX[0]

tensor([7, 8])

In [48]:
MATRIX.ndim

2

In [49]:
MATRIX.shape

torch.Size([2, 2])

In [50]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [51]:
TENSOR.ndim

3

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [54]:
#PRACTICE TENSORS 1
tensor1 = torch.tensor([1])
print(tensor1.ndim)
print(tensor1.shape)
print(tensor1[0])
tensor1


1
torch.Size([1])
tensor(1)


tensor([1])

In [55]:
#PRACTICE TENSORS 2
#tensor2 = torch.tensor([1],[2],[3])
#TypeError: tensor() takes 1 positional argument but 3 were given
#WE HAVE TO MAKE IT LIKE A 2D TENSOR OR WE CAN ADD INSIDE THE SINGLES WHICH WILL REMAIN A 1D TENSOR
tensor2 = torch.tensor([1,2,3,4,55,52,54,5,353])
print(tensor2.ndim)
print(tensor2.shape)
print(tensor2[4])
tensor2


1
torch.Size([9])
tensor(55)


tensor([  1,   2,   3,   4,  55,  52,  54,   5, 353])

In [56]:
#PRACTICE TENSORS 3
#The below code doesnt work cuz:
#ValueError: expected sequence of length 2 at dim 1 (got 3)
#tensor3 = torch.tensor([[1,2],
#                        [1,2,3],
#                        [4]])
tensor3 = torch.tensor([[1,2,3],
                        [11,12,13],
                        [4,5,6]])
print(tensor3.ndim)
print(tensor3.shape)
print(tensor3[2])
print(tensor3[1,2])
tensor3


2
torch.Size([3, 3])
tensor([4, 5, 6])
tensor(13)


tensor([[ 1,  2,  3],
        [11, 12, 13],
        [ 4,  5,  6]])

In [57]:
#PRACTICE TENSORS 4

tensor4 = torch.tensor([[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]])
print(tensor4.ndim)
print(tensor4.shape)
print(tensor4[2])
print(tensor4[1,2])
tensor4


2
torch.Size([4, 5])
tensor([44,  5,  6, 10,  5])
tensor(13)


tensor([[ 1,  2,  3,  4, 65],
        [11, 12, 13, 89, 56],
        [44,  5,  6, 10,  5],
        [ 1,  2,  3, 46,  6]])

In [58]:
#PRACTICE TENSORS 5

tensor5 = torch.tensor([[[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]]])
print(tensor5.ndim)
print(tensor5.shape)

#print(tensor5[2]) not possible cuz:
#IndexError: index 2 is out of bounds for dimension 0 with size SOOO....:
print(tensor5[0,1])

#print(tensor5[1,2]) not possible cuz:
#index 1 is out of bounds for dimension 0 with size 1 SOOOO....:
print(tensor5[0,2,3])

tensor5


3
torch.Size([1, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(10)


tensor([[[ 1,  2,  3,  4, 65],
         [11, 12, 13, 89, 56],
         [44,  5,  6, 10,  5],
         [ 1,  2,  3, 46,  6]]])

In [72]:
#PRACTICE TENSORS 6

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65]
#                        [11,12,13,89,56],[12,22,32,42]
#                        [44,5,6,10,5],[22,33,44,55,66]
#                        [1,2,3,46,6],[23,33,43,53]]])
#CUZ:   TypeError must be lists, not tuples, were missing commas and first are 5 while seconds were 4 ,have to be equal....SOOO..:

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65,11],
#                        [11,12,13,89,56],[12,22,32,42,22],
#                        [44,5,6,10,5],[22,33,44,55,200],
#                        [1,2,3,46,6],[23,33,43,53,100]]])
#works....but same as before with size[1,8,5]....

tensor6 = torch.tensor([
                        [[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]],

                          [[32,43,54,65,11],
                          [12,22,32,42,22],
                          [22,33,44,55,200],
                          [23,33,43,53,100]]
                        ])

print(tensor6.ndim)
print(tensor6.shape)

print(tensor6[0,1])

print(tensor6[1,2,3])

tensor6


3
torch.Size([2, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(55)


tensor([[[  1,   2,   3,   4,  65],
         [ 11,  12,  13,  89,  56],
         [ 44,   5,   6,  10,   5],
         [  1,   2,   3,  46,   6]],

        [[ 32,  43,  54,  65,  11],
         [ 12,  22,  32,  42,  22],
         [ 22,  33,  44,  55, 200],
         [ 23,  33,  43,  53, 100]]])

**END OF PRACTICE**

##**RANDOM tensors**
Why random tensors?

it starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with RND nums -> look at data ->update RND nums -> look at data -> update RND nums

More at: https://pytorch.org/docs/stable/generated/torch.rand.html

In [75]:
#Create a random tensor of size (3,4)
rand_tensor = torch.rand(11,4)
rand_tensor

tensor([[0.5767, 0.3525, 0.4336, 0.2396],
        [0.2905, 0.1090, 0.1268, 0.4660],
        [0.1992, 0.9980, 0.2645, 0.0635],
        [0.6243, 0.6633, 0.6405, 0.4431],
        [0.1966, 0.5169, 0.9895, 0.6731],
        [0.0196, 0.9694, 0.8384, 0.6073],
        [0.7504, 0.1307, 0.0881, 0.9924],
        [0.0991, 0.8545, 0.5908, 0.5204],
        [0.8758, 0.1943, 0.5474, 0.2410],
        [0.8514, 0.3558, 0.0771, 0.8637],
        [0.7606, 0.5919, 0.1962, 0.2136]])

In [74]:
rand_tensor.ndim

2

In [76]:
#Create a random tensor of size (2,4,5)
rand_tensor2 = torch.rand(2,4,5)
rand_tensor2

tensor([[[0.1774, 0.4767, 0.5775, 0.7591, 0.7657],
         [0.5147, 0.2779, 0.7129, 0.5372, 0.6302],
         [0.4485, 0.8602, 0.4746, 0.6425, 0.9925],
         [0.5866, 0.3416, 0.7972, 0.5173, 0.6187]],

        [[0.9634, 0.6156, 0.4531, 0.4496, 0.7716],
         [0.0688, 0.8176, 0.8358, 0.2943, 0.0722],
         [0.5467, 0.5979, 0.4823, 0.9749, 0.8160],
         [0.4987, 0.0334, 0.3028, 0.0650, 0.8917]]])

In [77]:
rand_tensor2.ndim

3

In [81]:
rand_tensor2 = torch.rand(2,3,4,5)
print(rand_tensor2.shape)
print(rand_tensor2.ndim)
rand_tensor2

torch.Size([2, 3, 4, 5])
4


tensor([[[[1.5312e-01, 8.4079e-01, 6.2286e-01, 8.1217e-01, 5.7584e-01],
          [2.2268e-01, 2.1215e-01, 4.0216e-01, 6.2646e-02, 7.9653e-01],
          [4.1413e-02, 3.4056e-01, 5.4492e-01, 3.5093e-01, 5.8390e-01],
          [7.5705e-02, 7.9759e-01, 8.1557e-01, 5.4106e-01, 1.4442e-01]],

         [[7.9129e-01, 2.8443e-01, 8.8768e-01, 1.0811e-02, 9.2326e-01],
          [1.4924e-01, 5.6913e-01, 9.3865e-02, 6.9634e-01, 1.5366e-01],
          [6.4506e-01, 7.5945e-01, 5.2425e-01, 7.2192e-01, 1.6097e-01],
          [4.2115e-01, 3.4137e-01, 3.9443e-01, 2.1791e-03, 4.5231e-01]],

         [[3.9381e-01, 3.1783e-01, 8.8487e-01, 3.7828e-01, 6.2473e-02],
          [9.5549e-01, 8.8310e-01, 1.2623e-01, 5.3063e-01, 2.0245e-01],
          [9.3569e-01, 9.8836e-01, 3.6025e-01, 8.1434e-01, 9.8817e-01],
          [3.5041e-01, 5.0347e-01, 9.5414e-01, 7.4952e-01, 9.6538e-01]]],


        [[[7.5572e-01, 2.8349e-01, 4.4227e-02, 3.1007e-01, 4.4563e-01],
          [7.5211e-01, 7.9565e-01, 2.2903e-01, 8.7672e-0

In [83]:
#Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(3,224,224)) #height,width,color channels(rgb)
random_img_size_tensor.shape,random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [91]:
#PRACTiCE:
rand_tensorrr = torch.rand(1,1,1,1,1,1,1)
print(rand_tensorrr.shape)
print(rand_tensorrr.ndim)
print(rand_tensorrr)

rand_tensorr = torch.rand(1,2,3,4)
print(rand_tensorr.shape)
print(rand_tensorr.ndim)
print(rand_tensorr)

rand_tensor3 = torch.rand(2,3,4,5)
print(rand_tensor3.shape)
print(rand_tensor3.ndim)
print(rand_tensor3)

rand_tensor5 = torch.rand(3,2,3,2,6)
print(rand_tensor5.shape)
print(rand_tensor5.ndim)
rand_tensor5

torch.Size([1, 1, 1, 1, 1, 1, 1])
7
tensor([[[[[[[0.9816]]]]]]])
torch.Size([1, 2, 3, 4])
4
tensor([[[[0.6004, 0.0218, 0.5347, 0.3939],
          [0.9536, 0.5717, 0.4542, 0.8649],
          [0.3657, 0.7784, 0.4063, 0.4725]],

         [[0.4199, 0.6707, 0.5319, 0.0347],
          [0.7559, 0.2989, 0.5678, 0.7638],
          [0.3647, 0.6304, 0.2739, 0.9572]]]])
torch.Size([2, 3, 4, 5])
4
tensor([[[[0.5439, 0.7638, 0.8546, 0.5316, 0.5021],
          [0.1552, 0.0146, 0.3300, 0.8460, 0.9542],
          [0.4637, 0.4956, 0.9746, 0.3745, 0.0821],
          [0.1816, 0.4136, 0.2655, 0.3973, 0.3015]],

         [[0.6906, 0.9791, 0.4465, 0.3721, 0.1583],
          [0.8873, 0.5120, 0.6617, 0.2208, 0.1498],
          [0.2205, 0.4362, 0.2714, 0.7831, 0.5569],
          [0.1567, 0.2455, 0.2458, 0.4441, 0.1397]],

         [[0.4209, 0.0788, 0.4533, 0.6347, 0.8441],
          [0.5225, 0.7861, 0.6203, 0.0039, 0.9046],
          [0.7826, 0.9228, 0.1062, 0.0728, 0.7233],
          [0.9249, 0.9896, 0.5847, 0

tensor([[[[[0.4795, 0.1810, 0.8424, 0.3874, 0.8215, 0.1195],
           [0.4586, 0.3936, 0.4300, 0.9607, 0.5108, 0.6853]],

          [[0.4481, 0.6488, 0.6205, 0.5399, 0.9802, 0.2610],
           [0.5901, 0.0884, 0.5789, 0.1589, 0.4299, 0.5596]],

          [[0.3653, 0.0817, 0.9937, 0.7669, 0.5476, 0.9375],
           [0.4518, 0.4586, 0.1137, 0.7535, 0.0629, 0.0291]]],


         [[[0.3742, 0.8002, 0.2561, 0.8388, 0.5480, 0.1476],
           [0.3498, 0.5405, 0.3327, 0.8456, 0.3844, 0.0759]],

          [[0.0709, 0.4148, 0.2828, 0.2511, 0.4349, 0.3065],
           [0.1487, 0.5341, 0.5856, 0.8943, 0.0026, 0.7529]],

          [[0.3219, 0.7866, 0.1672, 0.2986, 0.4142, 0.5514],
           [0.1709, 0.2087, 0.2167, 0.7693, 0.1144, 0.8171]]]],



        [[[[0.7035, 0.2683, 0.3250, 0.6993, 0.7278, 0.8315],
           [0.9666, 0.1046, 0.3593, 0.4057, 0.3936, 0.4134]],

          [[0.0884, 0.7117, 0.1122, 0.5842, 0.2526, 0.6207],
           [0.0718, 0.5946, 0.4052, 0.6832, 0.9084, 0.9441]],

  