<a href="https://colab.research.google.com/github/nnfuad/pytorch00/blob/main/00_pytorch_fund_vid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [35]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


In [36]:
!nvidia-smi

Sun Aug 18 15:42:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--


## Introduction to tensors
### way represent data(mostly multidimensional)

###Creating tensors

PyTorch tensors are created using `torch.tensor()` more at-https://pytorch.org/docs/stable/tensors.html

In [37]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [38]:
#scalar(0) doesnt work like matrices or vectors

##### many dimensions of scalar are there...to find out what dimension in scalar tensor: run `scalar.ndim`

In [39]:
scalar.ndim

0

###### get tensor back as py int use `item()`

In [40]:
scalar.item()

7

In [41]:
scalar.shape

torch.Size([])

##### vector has 2 values...Dimension and Shape

In [42]:
#vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [43]:
vector[1]

tensor(4)

##### many dimensions of scalar are there...to find out what dimension in vector tensor: run `vector.ndim`

In [44]:
vector.ndim

1

In [45]:
vector.shape

torch.Size([2])

In [46]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [47]:
MATRIX[0]

tensor([7, 8])

In [48]:
MATRIX.ndim

2

In [49]:
MATRIX.shape

torch.Size([2, 2])

In [50]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [51]:
TENSOR.ndim

3

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [54]:
#PRACTICE TENSORS 1
tensor1 = torch.tensor([1])
print(tensor1.ndim)
print(tensor1.shape)
print(tensor1[0])
tensor1


1
torch.Size([1])
tensor(1)


tensor([1])

In [55]:
#PRACTICE TENSORS 2
#tensor2 = torch.tensor([1],[2],[3])
#TypeError: tensor() takes 1 positional argument but 3 were given
#WE HAVE TO MAKE IT LIKE A 2D TENSOR OR WE CAN ADD INSIDE THE SINGLES WHICH WILL REMAIN A 1D TENSOR
tensor2 = torch.tensor([1,2,3,4,55,52,54,5,353])
print(tensor2.ndim)
print(tensor2.shape)
print(tensor2[4])
tensor2


1
torch.Size([9])
tensor(55)


tensor([  1,   2,   3,   4,  55,  52,  54,   5, 353])

In [56]:
#PRACTICE TENSORS 3
#The below code doesnt work cuz:
#ValueError: expected sequence of length 2 at dim 1 (got 3)
#tensor3 = torch.tensor([[1,2],
#                        [1,2,3],
#                        [4]])
tensor3 = torch.tensor([[1,2,3],
                        [11,12,13],
                        [4,5,6]])
print(tensor3.ndim)
print(tensor3.shape)
print(tensor3[2])
print(tensor3[1,2])
tensor3


2
torch.Size([3, 3])
tensor([4, 5, 6])
tensor(13)


tensor([[ 1,  2,  3],
        [11, 12, 13],
        [ 4,  5,  6]])

In [57]:
#PRACTICE TENSORS 4

tensor4 = torch.tensor([[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]])
print(tensor4.ndim)
print(tensor4.shape)
print(tensor4[2])
print(tensor4[1,2])
tensor4


2
torch.Size([4, 5])
tensor([44,  5,  6, 10,  5])
tensor(13)


tensor([[ 1,  2,  3,  4, 65],
        [11, 12, 13, 89, 56],
        [44,  5,  6, 10,  5],
        [ 1,  2,  3, 46,  6]])

In [58]:
#PRACTICE TENSORS 5

tensor5 = torch.tensor([[[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]]])
print(tensor5.ndim)
print(tensor5.shape)

#print(tensor5[2]) not possible cuz:
#IndexError: index 2 is out of bounds for dimension 0 with size SOOO....:
print(tensor5[0,1])

#print(tensor5[1,2]) not possible cuz:
#index 1 is out of bounds for dimension 0 with size 1 SOOOO....:
print(tensor5[0,2,3])

tensor5


3
torch.Size([1, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(10)


tensor([[[ 1,  2,  3,  4, 65],
         [11, 12, 13, 89, 56],
         [44,  5,  6, 10,  5],
         [ 1,  2,  3, 46,  6]]])