<a href="https://colab.research.google.com/github/nnfuad/pytorch00/blob/main/00_pytorch_fund_vid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [36]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


In [37]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found



## Introduction to tensors
### way represent data(mostly multidimensional)

###Creating tensors

PyTorch tensors are created using `torch.tensor()` more at-https://pytorch.org/docs/stable/tensors.html

In [38]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [39]:
#scalar(0) doesnt work like matrices or vectors

##### many dimensions of scalar are there...to find out what dimension in scalar tensor: run `scalar.ndim`

In [40]:
scalar.ndim

0

###### get tensor back as py int use `item()`

In [41]:
scalar.item()

7

In [42]:
scalar.shape

torch.Size([])

##### vector has 2 values...Dimension and Shape

In [43]:
#vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [44]:
vector[1]

tensor(4)

##### many dimensions of scalar are there...to find out what dimension in vector tensor: run `vector.ndim`

In [45]:
vector.ndim

1

In [46]:
vector.shape

torch.Size([2])

In [47]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [48]:
MATRIX[0]

tensor([7, 8])

In [49]:
MATRIX.ndim

2

In [50]:
MATRIX.shape

torch.Size([2, 2])

In [51]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [52]:
TENSOR.ndim

3

In [53]:
TENSOR.shape

torch.Size([1, 3, 3])

In [54]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [55]:
#PRACTICE TENSORS 1
tensor1 = torch.tensor([1])
print(tensor1.ndim)
print(tensor1.shape)
print(tensor1[0])
tensor1


1
torch.Size([1])
tensor(1)


tensor([1])

In [56]:
#PRACTICE TENSORS 2
#tensor2 = torch.tensor([1],[2],[3])
#TypeError: tensor() takes 1 positional argument but 3 were given
#WE HAVE TO MAKE IT LIKE A 2D TENSOR OR WE CAN ADD INSIDE THE SINGLES WHICH WILL REMAIN A 1D TENSOR
tensor2 = torch.tensor([1,2,3,4,55,52,54,5,353])
print(tensor2.ndim)
print(tensor2.shape)
print(tensor2[4])
tensor2


1
torch.Size([9])
tensor(55)


tensor([  1,   2,   3,   4,  55,  52,  54,   5, 353])

In [57]:
#PRACTICE TENSORS 3
#The below code doesnt work cuz:
#ValueError: expected sequence of length 2 at dim 1 (got 3)
#tensor3 = torch.tensor([[1,2],
#                        [1,2,3],
#                        [4]])
tensor3 = torch.tensor([[1,2,3],
                        [11,12,13],
                        [4,5,6]])
print(tensor3.ndim)
print(tensor3.shape)
print(tensor3[2])
print(tensor3[1,2])
tensor3


2
torch.Size([3, 3])
tensor([4, 5, 6])
tensor(13)


tensor([[ 1,  2,  3],
        [11, 12, 13],
        [ 4,  5,  6]])

In [58]:
#PRACTICE TENSORS 4

tensor4 = torch.tensor([[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]])
print(tensor4.ndim)
print(tensor4.shape)
print(tensor4[2])
print(tensor4[1,2])
tensor4


2
torch.Size([4, 5])
tensor([44,  5,  6, 10,  5])
tensor(13)


tensor([[ 1,  2,  3,  4, 65],
        [11, 12, 13, 89, 56],
        [44,  5,  6, 10,  5],
        [ 1,  2,  3, 46,  6]])

In [59]:
#PRACTICE TENSORS 5

tensor5 = torch.tensor([[[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]]])
print(tensor5.ndim)
print(tensor5.shape)

#print(tensor5[2]) not possible cuz:
#IndexError: index 2 is out of bounds for dimension 0 with size SOOO....:
print(tensor5[0,1])

#print(tensor5[1,2]) not possible cuz:
#index 1 is out of bounds for dimension 0 with size 1 SOOOO....:
print(tensor5[0,2,3])

tensor5


3
torch.Size([1, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(10)


tensor([[[ 1,  2,  3,  4, 65],
         [11, 12, 13, 89, 56],
         [44,  5,  6, 10,  5],
         [ 1,  2,  3, 46,  6]]])

In [60]:
#PRACTICE TENSORS 6

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65]
#                        [11,12,13,89,56],[12,22,32,42]
#                        [44,5,6,10,5],[22,33,44,55,66]
#                        [1,2,3,46,6],[23,33,43,53]]])
#CUZ:   TypeError must be lists, not tuples, were missing commas and first are 5 while seconds were 4 ,have to be equal....SOOO..:

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65,11],
#                        [11,12,13,89,56],[12,22,32,42,22],
#                        [44,5,6,10,5],[22,33,44,55,200],
#                        [1,2,3,46,6],[23,33,43,53,100]]])
#works....but same as before with size[1,8,5]....

tensor6 = torch.tensor([
                        [[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]],

                          [[32,43,54,65,11],
                          [12,22,32,42,22],
                          [22,33,44,55,200],
                          [23,33,43,53,100]]
                        ])

print(tensor6.ndim)
print(tensor6.shape)

print(tensor6[0,1])

print(tensor6[1,2,3])

tensor6


3
torch.Size([2, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(55)


tensor([[[  1,   2,   3,   4,  65],
         [ 11,  12,  13,  89,  56],
         [ 44,   5,   6,  10,   5],
         [  1,   2,   3,  46,   6]],

        [[ 32,  43,  54,  65,  11],
         [ 12,  22,  32,  42,  22],
         [ 22,  33,  44,  55, 200],
         [ 23,  33,  43,  53, 100]]])

**END OF PRACTICE**

##**RANDOM tensors**
Why random tensors?

it starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with RND nums -> look at data ->update RND nums -> look at data -> update RND nums

More at: https://pytorch.org/docs/stable/generated/torch.rand.html

In [61]:
#Create a random tensor of size (3,4)
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.3993, 0.3759, 0.1561, 0.2324],
        [0.2690, 0.1359, 0.9811, 0.8101],
        [0.0823, 0.8078, 0.7789, 0.1115]])

In [62]:
rand_tensor.ndim

2

In [63]:
#Create a random tensor of size (2,4,5)
rand_tensor2 = torch.rand(2,4,5)
rand_tensor2

tensor([[[0.4132, 0.9291, 0.1086, 0.8106, 0.3129],
         [0.0170, 0.7003, 0.9457, 0.7237, 0.0294],
         [0.7369, 0.0980, 0.3657, 0.8207, 0.9226],
         [0.5537, 0.7462, 0.7474, 0.3566, 0.8407]],

        [[0.1818, 0.5714, 0.0707, 0.1533, 0.1947],
         [0.9814, 0.3022, 0.4797, 0.1147, 0.8079],
         [0.6433, 0.8503, 0.1117, 0.3944, 0.2954],
         [0.7757, 0.1552, 0.4347, 0.3472, 0.9482]]])

In [64]:
rand_tensor2.ndim

3

In [65]:
rand_tensor2 = torch.rand(2,3,4,5)
print(rand_tensor2.shape)
print(rand_tensor2.ndim)
rand_tensor2

torch.Size([2, 3, 4, 5])
4


tensor([[[[0.7889, 0.2565, 0.1404, 0.1093, 0.2244],
          [0.8088, 0.7555, 0.5051, 0.6495, 0.8700],
          [0.3406, 0.6264, 0.4986, 0.8417, 0.8429],
          [0.9468, 0.3278, 0.4504, 0.4751, 0.0563]],

         [[0.5674, 0.0800, 0.0495, 0.6411, 0.3863],
          [0.6184, 0.7697, 0.0071, 0.4809, 0.5063],
          [0.2325, 0.5051, 0.2626, 0.8593, 0.7141],
          [0.9521, 0.7498, 0.9949, 0.8692, 0.4393]],

         [[0.6110, 0.5414, 0.3684, 0.8132, 0.1907],
          [0.9343, 0.3133, 0.9663, 0.3135, 0.7724],
          [0.0764, 0.3618, 0.2640, 0.5443, 0.9046],
          [0.2465, 0.6279, 0.2370, 0.9568, 0.6906]]],


        [[[0.1011, 0.6887, 0.5221, 0.4450, 0.1650],
          [0.9607, 0.5193, 0.8203, 0.6708, 0.6058],
          [0.0889, 0.8422, 0.0341, 0.8791, 0.8384],
          [0.7098, 0.1137, 0.1481, 0.4233, 0.9976]],

         [[0.6423, 0.0825, 0.8278, 0.6609, 0.4353],
          [0.8121, 0.0926, 0.6458, 0.5093, 0.4363],
          [0.6164, 0.4374, 0.5143, 0.8086, 0.8794],
  

In [66]:
#Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(3,224,224)) #height,width,color channels(rgb)
random_img_size_tensor.shape,random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [67]:
#PRACTiCE:
rand_tensorrr = torch.rand(1,1,1,1,1,1,1)
print(rand_tensorrr.shape)
print(rand_tensorrr.ndim)
print(rand_tensorrr)

rand_tensorr = torch.rand(1,2,3,4)
print(rand_tensorr.shape)
print(rand_tensorr.ndim)
print(rand_tensorr)

rand_tensor3 = torch.rand(2,3,4,5)
print(rand_tensor3.shape)
print(rand_tensor3.ndim)
print(rand_tensor3)

rand_tensor5 = torch.rand(3,2,3,2,6)
print(rand_tensor5.shape)
print(rand_tensor5.ndim)
rand_tensor5

torch.Size([1, 1, 1, 1, 1, 1, 1])
7
tensor([[[[[[[0.4128]]]]]]])
torch.Size([1, 2, 3, 4])
4
tensor([[[[0.1330, 0.5487, 0.9920, 0.8781],
          [0.5431, 0.2255, 0.8167, 0.5996],
          [0.4683, 0.4503, 0.7683, 0.4300]],

         [[0.2720, 0.3892, 0.2923, 0.6396],
          [0.5844, 0.9625, 0.8689, 0.3031],
          [0.6979, 0.3992, 0.0066, 0.2111]]]])
torch.Size([2, 3, 4, 5])
4
tensor([[[[9.9269e-01, 2.5266e-01, 9.8726e-01, 9.8659e-01, 9.8592e-01],
          [3.2680e-01, 8.9106e-01, 3.4887e-01, 5.4131e-01, 7.0176e-01],
          [1.7414e-01, 1.4640e-01, 9.3426e-01, 3.3881e-01, 4.6461e-01],
          [5.6925e-01, 1.4234e-01, 4.3848e-01, 8.9970e-01, 9.2423e-01]],

         [[2.0206e-01, 8.0971e-01, 4.3622e-01, 6.4440e-01, 5.6815e-01],
          [6.2784e-01, 6.0456e-01, 7.8417e-01, 6.6236e-01, 8.6132e-01],
          [1.7848e-01, 9.7923e-02, 5.1928e-01, 5.8581e-01, 5.1958e-01],
          [8.5582e-01, 3.5898e-01, 8.2396e-01, 8.0861e-01, 3.0344e-01]],

         [[7.5470e-01, 5.9045e-0

tensor([[[[[0.1555, 0.9027, 0.5612, 0.3048, 0.1623, 0.8863],
           [0.4617, 0.4285, 0.4911, 0.4032, 0.8531, 0.3537]],

          [[0.6444, 0.5470, 0.1738, 0.4399, 0.6700, 0.4175],
           [0.6959, 0.7389, 0.1427, 0.9652, 0.4425, 0.1759]],

          [[0.9074, 0.7071, 0.9263, 0.9082, 0.5174, 0.4380],
           [0.8172, 0.9389, 0.5165, 0.0475, 0.9590, 0.3663]]],


         [[[0.4433, 0.8723, 0.4233, 0.6723, 0.3841, 0.2268],
           [0.7239, 0.8180, 0.1994, 0.4079, 0.3710, 0.8769]],

          [[0.7231, 0.6783, 0.2915, 0.3996, 0.2473, 0.7170],
           [0.5106, 0.3493, 0.9200, 0.8386, 0.3135, 0.8846]],

          [[0.6075, 0.4251, 0.3385, 0.1995, 0.7320, 0.1931],
           [0.1292, 0.9324, 0.1510, 0.1217, 0.2788, 0.6474]]]],



        [[[[0.2056, 0.2199, 0.4733, 0.2265, 0.8451, 0.5039],
           [0.6340, 0.3268, 0.8226, 0.3721, 0.0839, 0.4658]],

          [[0.4761, 0.1233, 0.1965, 0.2355, 0.6957, 0.7872],
           [0.3851, 0.8364, 0.3502, 0.0910, 0.0909, 0.1206]],

  

###Zeros and ones

In [68]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
ones.dtype

torch.float32

In [73]:
ones*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [76]:
# Use torch.range()
one_to_ten = torch.arange(0,1000,78)
one_to_ten

tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])

In [78]:
# Tensor like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
two_to_ten_like = torch.ones_like(input=one_to_ten)
two_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])