<a href="https://colab.research.google.com/github/nnfuad/pytorch00/blob/main/00_pytorch_fund_vid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found



## Introduction to tensors
### way represent data(mostly multidimensional)

###Creating tensors

PyTorch tensors are created using `torch.tensor()` more at-https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#scalar(0) doesnt work like matrices or vectors

##### many dimensions of scalar are there...to find out what dimension in scalar tensor: run `scalar.ndim`

In [5]:
scalar.ndim

0

###### get tensor back as py int use `item()`

In [6]:
scalar.item()

7

In [7]:
scalar.shape

torch.Size([])

##### vector has 2 values...Dimension and Shape

In [8]:
#vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [9]:
vector[1]

tensor(4)

##### many dimensions of scalar are there...to find out what dimension in vector tensor: run `vector.ndim`

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [20]:
#PRACTICE TENSORS 1
tensor1 = torch.tensor([1])
print(tensor1.ndim)
print(tensor1.shape)
print(tensor1[0])
tensor1


1
torch.Size([1])
tensor(1)


tensor([1])

In [21]:
#PRACTICE TENSORS 2
#tensor2 = torch.tensor([1],[2],[3])
#TypeError: tensor() takes 1 positional argument but 3 were given
#WE HAVE TO MAKE IT LIKE A 2D TENSOR OR WE CAN ADD INSIDE THE SINGLES WHICH WILL REMAIN A 1D TENSOR
tensor2 = torch.tensor([1,2,3,4,55,52,54,5,353])
print(tensor2.ndim)
print(tensor2.shape)
print(tensor2[4])
tensor2


1
torch.Size([9])
tensor(55)


tensor([  1,   2,   3,   4,  55,  52,  54,   5, 353])

In [22]:
#PRACTICE TENSORS 3
#The below code doesnt work cuz:
#ValueError: expected sequence of length 2 at dim 1 (got 3)
#tensor3 = torch.tensor([[1,2],
#                        [1,2,3],
#                        [4]])
tensor3 = torch.tensor([[1,2,3],
                        [11,12,13],
                        [4,5,6]])
print(tensor3.ndim)
print(tensor3.shape)
print(tensor3[2])
print(tensor3[1,2])
tensor3


2
torch.Size([3, 3])
tensor([4, 5, 6])
tensor(13)


tensor([[ 1,  2,  3],
        [11, 12, 13],
        [ 4,  5,  6]])

In [23]:
#PRACTICE TENSORS 4

tensor4 = torch.tensor([[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]])
print(tensor4.ndim)
print(tensor4.shape)
print(tensor4[2])
print(tensor4[1,2])
tensor4


2
torch.Size([4, 5])
tensor([44,  5,  6, 10,  5])
tensor(13)


tensor([[ 1,  2,  3,  4, 65],
        [11, 12, 13, 89, 56],
        [44,  5,  6, 10,  5],
        [ 1,  2,  3, 46,  6]])

In [24]:
#PRACTICE TENSORS 5

tensor5 = torch.tensor([[[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]]])
print(tensor5.ndim)
print(tensor5.shape)

#print(tensor5[2]) not possible cuz:
#IndexError: index 2 is out of bounds for dimension 0 with size SOOO....:
print(tensor5[0,1])

#print(tensor5[1,2]) not possible cuz:
#index 1 is out of bounds for dimension 0 with size 1 SOOOO....:
print(tensor5[0,2,3])

tensor5


3
torch.Size([1, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(10)


tensor([[[ 1,  2,  3,  4, 65],
         [11, 12, 13, 89, 56],
         [44,  5,  6, 10,  5],
         [ 1,  2,  3, 46,  6]]])

In [25]:
#PRACTICE TENSORS 6

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65]
#                        [11,12,13,89,56],[12,22,32,42]
#                        [44,5,6,10,5],[22,33,44,55,66]
#                        [1,2,3,46,6],[23,33,43,53]]])
#CUZ:   TypeError must be lists, not tuples, were missing commas and first are 5 while seconds were 4 ,have to be equal....SOOO..:

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65,11],
#                        [11,12,13,89,56],[12,22,32,42,22],
#                        [44,5,6,10,5],[22,33,44,55,200],
#                        [1,2,3,46,6],[23,33,43,53,100]]])
#works....but same as before with size[1,8,5]....

tensor6 = torch.tensor([
                        [[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]],

                          [[32,43,54,65,11],
                          [12,22,32,42,22],
                          [22,33,44,55,200],
                          [23,33,43,53,100]]
                        ])

print(tensor6.ndim)
print(tensor6.shape)

print(tensor6[0,1])

print(tensor6[1,2,3])

tensor6


3
torch.Size([2, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(55)


tensor([[[  1,   2,   3,   4,  65],
         [ 11,  12,  13,  89,  56],
         [ 44,   5,   6,  10,   5],
         [  1,   2,   3,  46,   6]],

        [[ 32,  43,  54,  65,  11],
         [ 12,  22,  32,  42,  22],
         [ 22,  33,  44,  55, 200],
         [ 23,  33,  43,  53, 100]]])

**END OF PRACTICE**

##**RANDOM tensors**
Why random tensors?

it starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with RND nums -> look at data ->update RND nums -> look at data -> update RND nums

More at: https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
#Create a random tensor of size (3,4)
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.9530, 0.6089, 0.2584, 0.5684],
        [0.9328, 0.4052, 0.4983, 0.0188],
        [0.6290, 0.4254, 0.1882, 0.5370]])

In [27]:
rand_tensor.ndim

2

In [28]:
#Create a random tensor of size (2,4,5)
rand_tensor2 = torch.rand(2,4,5)
rand_tensor2

tensor([[[0.8603, 0.8400, 0.8985, 0.2690, 0.0542],
         [0.8773, 0.3683, 0.2073, 0.9558, 0.4076],
         [0.8186, 0.3929, 0.3455, 0.4852, 0.5938],
         [0.8381, 0.6644, 0.1002, 0.5800, 0.8807]],

        [[0.2496, 0.3368, 0.6909, 0.4215, 0.2170],
         [0.5199, 0.8878, 0.2166, 0.3672, 0.4575],
         [0.8415, 0.6029, 0.3966, 0.3735, 0.5275],
         [0.3814, 0.7142, 0.0741, 0.0623, 0.4968]]])

In [29]:
rand_tensor2.ndim

3

In [30]:
rand_tensor2 = torch.rand(2,3,4,5)
print(rand_tensor2.shape)
print(rand_tensor2.ndim)
rand_tensor2

torch.Size([2, 3, 4, 5])
4


tensor([[[[0.2512, 0.1974, 0.0543, 0.8094, 0.4467],
          [0.5666, 0.8991, 0.2334, 0.8193, 0.4313],
          [0.8343, 0.2189, 0.0808, 0.2064, 0.3890],
          [0.4248, 0.5160, 0.9875, 0.2066, 0.7494]],

         [[0.8121, 0.3487, 0.7436, 0.5868, 0.5162],
          [0.0343, 0.8344, 0.0452, 0.3218, 0.5596],
          [0.8942, 0.3465, 0.7043, 0.3038, 0.5799],
          [0.3721, 0.7450, 0.9707, 0.2367, 0.5333]],

         [[0.6602, 0.1316, 0.1761, 0.3741, 0.5240],
          [0.4760, 0.5649, 0.0770, 0.6723, 0.4858],
          [0.2043, 0.2471, 0.4026, 0.1824, 0.4535],
          [0.1740, 0.9831, 0.1917, 0.5144, 0.9959]]],


        [[[0.1944, 0.3946, 0.7666, 0.5427, 0.0576],
          [0.9304, 0.9019, 0.8794, 0.6494, 0.3260],
          [0.1018, 0.3159, 0.1934, 0.6921, 0.2343],
          [0.6922, 0.3223, 0.8862, 0.9607, 0.6490]],

         [[0.1472, 0.7147, 0.1885, 0.2002, 0.2493],
          [0.7615, 0.0190, 0.2933, 0.6820, 0.0054],
          [0.0442, 0.9824, 0.5429, 0.1380, 0.2515],
  

In [31]:
#Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(3,224,224)) #height,width,color channels(rgb)
random_img_size_tensor.shape,random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [32]:
#PRACTiCE:
rand_tensorrr = torch.rand(1,1,1,1,1,1,1)
print(rand_tensorrr.shape)
print(rand_tensorrr.ndim)
print(rand_tensorrr)

rand_tensorr = torch.rand(1,2,3,4)
print(rand_tensorr.shape)
print(rand_tensorr.ndim)
print(rand_tensorr)

rand_tensor3 = torch.rand(2,3,4,5)
print(rand_tensor3.shape)
print(rand_tensor3.ndim)
print(rand_tensor3)

rand_tensor5 = torch.rand(3,2,3,2,6)
print(rand_tensor5.shape)
print(rand_tensor5.ndim)
rand_tensor5

torch.Size([1, 1, 1, 1, 1, 1, 1])
7
tensor([[[[[[[0.7783]]]]]]])
torch.Size([1, 2, 3, 4])
4
tensor([[[[0.9636, 0.3956, 0.1105, 0.8492],
          [0.3782, 0.0558, 0.5951, 0.2464],
          [0.5061, 0.8174, 0.1669, 0.8678]],

         [[0.3484, 0.8149, 0.5257, 0.7717],
          [0.0838, 0.9166, 0.3997, 0.0714],
          [0.7041, 0.1701, 0.7975, 0.6540]]]])
torch.Size([2, 3, 4, 5])
4
tensor([[[[0.2463, 0.4767, 0.3195, 0.3849, 0.8372],
          [0.3926, 0.3476, 0.8499, 0.8666, 0.3411],
          [0.1150, 0.9333, 0.8824, 0.4042, 0.4335],
          [0.1534, 0.9447, 0.1106, 0.5083, 0.3954]],

         [[0.4297, 0.7930, 0.2564, 0.5841, 0.3027],
          [0.5303, 0.1188, 0.3543, 0.3880, 0.1479],
          [0.2387, 0.6756, 0.2261, 0.5816, 0.3813],
          [0.8243, 0.6253, 0.9788, 0.4204, 0.1442]],

         [[0.5855, 0.1228, 0.5964, 0.7112, 0.8714],
          [0.8354, 0.6359, 0.1507, 0.4942, 0.8304],
          [0.3958, 0.8504, 0.5226, 0.9508, 0.8280],
          [0.2459, 0.6990, 0.5018, 0

tensor([[[[[0.7813, 0.8305, 0.7303, 0.1908, 0.1856, 0.0654],
           [0.5670, 0.6475, 0.1087, 0.4477, 0.0753, 0.9404]],

          [[0.8886, 0.8998, 0.5379, 0.3238, 0.2815, 0.8297],
           [0.1301, 0.7158, 0.9822, 0.8145, 0.2638, 0.6412]],

          [[0.3090, 0.3347, 0.2931, 0.2645, 0.0234, 0.6884],
           [0.5407, 0.0985, 0.1139, 0.4069, 0.3095, 0.7462]]],


         [[[0.0063, 0.4025, 0.3911, 0.9215, 0.0680, 0.3560],
           [0.7666, 0.9982, 0.0243, 0.7272, 0.6796, 0.4633]],

          [[0.6774, 0.5199, 0.4886, 0.2494, 0.3079, 0.3875],
           [0.0465, 0.1829, 0.4550, 0.4984, 0.5675, 0.1103]],

          [[0.8394, 0.2634, 0.8723, 0.6872, 0.2758, 0.0394],
           [0.6349, 0.8093, 0.8248, 0.3332, 0.8646, 0.4498]]]],



        [[[[0.4582, 0.3433, 0.1908, 0.9178, 0.7781, 0.7368],
           [0.8312, 0.6120, 0.0533, 0.3865, 0.1777, 0.1331]],

          [[0.2027, 0.7396, 0.2667, 0.2134, 0.2940, 0.9339],
           [0.2986, 0.1344, 0.2961, 0.8896, 0.2558, 0.9125]],

  

###Zeros and ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

In [37]:
ones*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [38]:
# Use torch.range()
one_to_ten = torch.arange(0,1000,78)
one_to_ten

tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])

In [39]:
# Tensor like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
two_to_ten_like = torch.ones_like(input=one_to_ten)
two_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Data Type

**Note:** Tensor data types is one of the 3 big errors you may run into with PyTorch & deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

  Learn more about precision incomputing here:
  https://en.wikipedia.org/wiki/Precision_(computer_science)

In [41]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what datatype is the tensor(e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [44]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [45]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [46]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [47]:
int_long_tensor = torch.tensor([3,6,9], dtype= torch.long)
int_long_tensor

tensor([3, 6, 9])

In [48]:
float_32_tensor * int_long_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

  1. Tensors not right datatype - to do get datatype from a tensor,can use `tensor.type`
  2. Tensors not right shape - to get shape from a tensor use `tensor.shape`
  3. Tensors not on the right device - to get device from tensor use `tensor.device`

In [49]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8710, 0.4666, 0.6890, 0.7721],
        [0.4570, 0.1480, 0.8299, 0.5469],
        [0.7609, 0.7106, 0.7863, 0.9455]])

In [50]:
# Find details of Tensor

print(some_tensor)
print("Datatype of tensor: "+str(some_tensor.dtype))
print(f"Shape of tensor {some_tensor.shape}")
print(f"Device tensor is {some_tensor.device}")

tensor([[0.8710, 0.4666, 0.6890, 0.7721],
        [0.4570, 0.1480, 0.8299, 0.5469],
        [0.7609, 0.7106, 0.7863, 0.9455]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu


In [51]:
# Practice
some_tensor2 = torch.rand(3,4)
print(some_tensor2)
print("Datatype of tensor: "+str(some_tensor2.dtype))
print(f"Shape of tensor {some_tensor2.shape}")
print(f"Device tensor is {some_tensor2.device}")

some_tensor3 = torch.rand(3,4)
print(some_tensor3)
print("Datatype of tensor: "+str(some_tensor3.dtype))
print(f"Shape of tensor {some_tensor3.shape}")
print(f"Device tensor is {some_tensor3.device}")

tensor([[0.1661, 0.6738, 0.7662, 0.0573],
        [0.4411, 0.8402, 0.0159, 0.6367],
        [0.9919, 0.4268, 0.9752, 0.0879]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu
tensor([[0.8511, 0.7192, 0.4953, 0.9810],
        [0.0644, 0.5511, 0.3254, 0.4146],
        [0.0013, 0.8512, 0.9417, 0.2026]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu


### Manipulating tensors (tensor operations)

Tensor operations include
* Addition
* Substraction
* Multiplications (elementwise)
* Division
* Matrix multiplication

In [52]:
# Create a tensor
tensor = torch.tensor([1,2,3])

#addition
tensor+10

tensor([11, 12, 13])

In [53]:
#multiply (elementwise)
tensor*10

tensor([10, 20, 30])

In [54]:
#Try out PyTorch in-built funstions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [55]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [56]:
tensor%3

tensor([1, 2, 0])

## Matrix Multiplication

Two main ways of performing multiplication in DL:

1. Elementwise
2. Matrix Multiplication (dot product)
In PyTorch we use `torch.matmul(tensor_1,tensor_2)` or **tensor1@tensor2** or `torch.mm(tensor_1,tensor_2)`

Here can be found more: https://www.mathisfun.com/algebra/matrix-multiplying.html

### Two of the most important rules in matrix mult are:

1. The **inner dimensions must match**


*   (3,2) @ (3,2) won't work || matmul(torch.rand(3,2),torch.rand(3,2))
*   (2,3) @ (3,2) will work || matmul(torch.rand(2,3),torch.rand(3,2))
*   (3,2) @ (2,3) will work || matmul(torch.rand(3,2),torch.rand(2,3))



In [57]:
# Element wise Multiplication
print(tensor,"*",tensor)
print("Equals",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [58]:
# Matrix Multiplication

print(tensor,".",tensor)
print("Equals ",torch.matmul(tensor,tensor))

tensor([1, 2, 3]) . tensor([1, 2, 3])
Equals  tensor(14)


In [59]:
# Matrix Multiplication by hand

1*1 + 2*2 + 3*3

14

In [60]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.09 ms, sys: 0 ns, total: 2.09 ms
Wall time: 3.28 ms


In [61]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 86 µs, sys: 0 ns, total: 86 µs
Wall time: 90.4 µs


tensor(14)

### One of the most common errors in DL: `Shape Errors`

In [62]:
# Shape for a matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A,tensor_B)

To fix shapes:
we can manipulate the shape of a matrix by transposing it.

A `transpose` switches the axes or dims of a given sensor

syntax: `matrix_A.T`

In [63]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [64]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [65]:
torch.mm(tensor_A,tensor_B.T),torch.mm(tensor_A,tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

##Finding the min,max,mean,sum,etc (tensor aggregation)

In [66]:
#Create a tensor
x= torch.arange(1,100,10)
x,x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [67]:
#Find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [68]:
#Find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [69]:
# Find the mean - note: torch.mean requires a tensor of float32 dtype to work, .arange is Long type
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [70]:
# Find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## Find the positional min and max

In [71]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
#Find the position in tensor tha has the minimum value with `argmin()` -> returns index
x.argmin()

tensor(0)

In [73]:
#Find the position in tensor tha has the minimum value with `argmin()` -> returns index
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other (vstack) or side by side (`hstack`)

* Squeeze - removes all `1` dimensions from a tensor

* Unsqueeze - add a `1` dimension to a target tensor

* Permute - Return a view of the input with dims permuted(swapped) in a certain way

In [74]:
# Create a tensor
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [75]:
# Add an extra dimension
x_reshaped1 = x.reshape(1,9)
x_reshaped1, x_reshaped1.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [76]:
x_reshaped2 = x.reshape(9,1)
x_reshaped2,x_reshaped2.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [77]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [88]:
# Changing z changes x (because a view of a tensor shares the same memory )
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [79]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [81]:
#torch.squeeze() - removes all single dims from target tensor
print(f"Porevious tensor: {x_reshaped1}")
print(f"Previous shape: {x_reshaped1.shape}")

#Remove extra dim from x_reshaped1
x_squeezed = x_reshaped1.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Porevious tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [87]:
#torch.unsqueeze(). - adds a single dim to a target tensor
print(f"Porevious tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Remove extra dim from x_reshaped1
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Porevious tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])
