<a href="https://colab.research.google.com/github/nnfuad/pytorch00/blob/main/00_pytorch_fund_vid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. Pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found



## Introduction to tensors
### way represent data(mostly multidimensional)

###Creating tensors

PyTorch tensors are created using `torch.tensor()` more at-https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#scalar(0) doesnt work like matrices or vectors

##### many dimensions of scalar are there...to find out what dimension in scalar tensor: run `scalar.ndim`

In [6]:
scalar.ndim

0

###### get tensor back as py int use `item()`

In [7]:
scalar.item()

7

In [8]:
scalar.shape

torch.Size([])

##### vector has 2 values...Dimension and Shape

In [9]:
#vector
vector = torch.tensor([7, 4])
vector

tensor([7, 4])

In [10]:
vector[1]

tensor(4)

##### many dimensions of scalar are there...to find out what dimension in vector tensor: run `vector.ndim`

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [21]:
#PRACTICE TENSORS 1
tensor1 = torch.tensor([1])
print(tensor1.ndim)
print(tensor1.shape)
print(tensor1[0])
tensor1


1
torch.Size([1])
tensor(1)


tensor([1])

In [22]:
#PRACTICE TENSORS 2
#tensor2 = torch.tensor([1],[2],[3])
#TypeError: tensor() takes 1 positional argument but 3 were given
#WE HAVE TO MAKE IT LIKE A 2D TENSOR OR WE CAN ADD INSIDE THE SINGLES WHICH WILL REMAIN A 1D TENSOR
tensor2 = torch.tensor([1,2,3,4,55,52,54,5,353])
print(tensor2.ndim)
print(tensor2.shape)
print(tensor2[4])
tensor2


1
torch.Size([9])
tensor(55)


tensor([  1,   2,   3,   4,  55,  52,  54,   5, 353])

In [23]:
#PRACTICE TENSORS 3
#The below code doesnt work cuz:
#ValueError: expected sequence of length 2 at dim 1 (got 3)
#tensor3 = torch.tensor([[1,2],
#                        [1,2,3],
#                        [4]])
tensor3 = torch.tensor([[1,2,3],
                        [11,12,13],
                        [4,5,6]])
print(tensor3.ndim)
print(tensor3.shape)
print(tensor3[2])
print(tensor3[1,2])
tensor3


2
torch.Size([3, 3])
tensor([4, 5, 6])
tensor(13)


tensor([[ 1,  2,  3],
        [11, 12, 13],
        [ 4,  5,  6]])

In [24]:
#PRACTICE TENSORS 4

tensor4 = torch.tensor([[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]])
print(tensor4.ndim)
print(tensor4.shape)
print(tensor4[2])
print(tensor4[1,2])
tensor4


2
torch.Size([4, 5])
tensor([44,  5,  6, 10,  5])
tensor(13)


tensor([[ 1,  2,  3,  4, 65],
        [11, 12, 13, 89, 56],
        [44,  5,  6, 10,  5],
        [ 1,  2,  3, 46,  6]])

In [25]:
#PRACTICE TENSORS 5

tensor5 = torch.tensor([[[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]]])
print(tensor5.ndim)
print(tensor5.shape)

#print(tensor5[2]) not possible cuz:
#IndexError: index 2 is out of bounds for dimension 0 with size SOOO....:
print(tensor5[0,1])

#print(tensor5[1,2]) not possible cuz:
#index 1 is out of bounds for dimension 0 with size 1 SOOOO....:
print(tensor5[0,2,3])

tensor5


3
torch.Size([1, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(10)


tensor([[[ 1,  2,  3,  4, 65],
         [11, 12, 13, 89, 56],
         [44,  5,  6, 10,  5],
         [ 1,  2,  3, 46,  6]]])

In [26]:
#PRACTICE TENSORS 6

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65]
#                        [11,12,13,89,56],[12,22,32,42]
#                        [44,5,6,10,5],[22,33,44,55,66]
#                        [1,2,3,46,6],[23,33,43,53]]])
#CUZ:   TypeError must be lists, not tuples, were missing commas and first are 5 while seconds were 4 ,have to be equal....SOOO..:

#tensor6 = torch.tensor([[[1,2,3,4,65],[32,43,54,65,11],
#                        [11,12,13,89,56],[12,22,32,42,22],
#                        [44,5,6,10,5],[22,33,44,55,200],
#                        [1,2,3,46,6],[23,33,43,53,100]]])
#works....but same as before with size[1,8,5]....

tensor6 = torch.tensor([
                        [[1,2,3,4,65],
                        [11,12,13,89,56],
                        [44,5,6,10,5],
                        [1,2,3,46,6]],

                          [[32,43,54,65,11],
                          [12,22,32,42,22],
                          [22,33,44,55,200],
                          [23,33,43,53,100]]
                        ])

print(tensor6.ndim)
print(tensor6.shape)

print(tensor6[0,1])

print(tensor6[1,2,3])

tensor6


3
torch.Size([2, 4, 5])
tensor([11, 12, 13, 89, 56])
tensor(55)


tensor([[[  1,   2,   3,   4,  65],
         [ 11,  12,  13,  89,  56],
         [ 44,   5,   6,  10,   5],
         [  1,   2,   3,  46,   6]],

        [[ 32,  43,  54,  65,  11],
         [ 12,  22,  32,  42,  22],
         [ 22,  33,  44,  55, 200],
         [ 23,  33,  43,  53, 100]]])

**END OF PRACTICE**

##**RANDOM tensors**
Why random tensors?

it starts with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with RND nums -> look at data ->update RND nums -> look at data -> update RND nums

More at: https://pytorch.org/docs/stable/generated/torch.rand.html

In [27]:
#Create a random tensor of size (3,4)
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.5743, 0.2038, 0.5936, 0.6850],
        [0.1867, 0.2730, 0.6483, 0.9214],
        [0.0033, 0.8798, 0.6692, 0.8258]])

In [28]:
rand_tensor.ndim

2

In [29]:
#Create a random tensor of size (2,4,5)
rand_tensor2 = torch.rand(2,4,5)
rand_tensor2

tensor([[[0.3972, 0.7871, 0.6572, 0.8269, 0.0462],
         [0.2704, 0.3912, 0.1302, 0.9131, 0.8889],
         [0.1820, 0.5466, 0.8955, 0.3769, 0.7540],
         [0.7599, 0.9184, 0.0881, 0.7864, 0.6407]],

        [[0.3313, 0.8804, 0.3904, 0.0147, 0.2780],
         [0.2241, 0.5201, 0.3655, 0.3826, 0.1124],
         [0.9438, 0.8412, 0.6633, 0.2440, 0.6219],
         [0.3048, 0.7770, 0.5694, 0.2392, 0.0438]]])

In [30]:
rand_tensor2.ndim

3

In [31]:
rand_tensor2 = torch.rand(2,3,4,5)
print(rand_tensor2.shape)
print(rand_tensor2.ndim)
rand_tensor2

torch.Size([2, 3, 4, 5])
4


tensor([[[[0.1445, 0.0295, 0.8653, 0.2200, 0.7191],
          [0.6411, 0.1002, 0.9959, 0.4902, 0.9447],
          [0.4715, 0.7862, 0.0801, 0.2962, 0.2584],
          [0.6515, 0.1942, 0.4742, 0.1525, 0.9790]],

         [[0.8450, 0.4462, 0.8852, 0.9914, 0.7053],
          [0.0946, 0.1040, 0.5482, 0.5046, 0.5557],
          [0.9389, 0.1895, 0.0326, 0.6327, 0.0725],
          [0.5775, 0.2523, 0.0339, 0.0425, 0.6576]],

         [[0.1747, 0.0594, 0.2309, 0.6180, 0.8672],
          [0.5780, 0.8836, 0.4923, 0.7466, 0.4899],
          [0.6112, 0.3607, 0.8670, 0.8087, 0.1184],
          [0.3596, 0.7087, 0.0332, 0.7226, 0.3114]]],


        [[[0.5881, 0.9366, 0.2102, 0.4081, 0.8221],
          [0.8440, 0.7628, 0.5578, 0.2776, 0.4905],
          [0.4576, 0.3010, 0.7096, 0.5978, 0.8612],
          [0.4065, 0.6901, 0.5577, 0.3935, 0.7779]],

         [[0.9726, 0.4182, 0.6115, 0.8491, 0.3894],
          [0.3721, 0.5134, 0.9738, 0.8466, 0.0216],
          [0.8556, 0.0560, 0.2665, 0.4297, 0.5930],
  

In [32]:
#Create a random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(3,224,224)) #height,width,color channels(rgb)
random_img_size_tensor.shape,random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [33]:
#PRACTiCE:
rand_tensorrr = torch.rand(1,1,1,1,1,1,1)
print(rand_tensorrr.shape)
print(rand_tensorrr.ndim)
print(rand_tensorrr)

rand_tensorr = torch.rand(1,2,3,4)
print(rand_tensorr.shape)
print(rand_tensorr.ndim)
print(rand_tensorr)

rand_tensor3 = torch.rand(2,3,4,5)
print(rand_tensor3.shape)
print(rand_tensor3.ndim)
print(rand_tensor3)

rand_tensor5 = torch.rand(3,2,3,2,6)
print(rand_tensor5.shape)
print(rand_tensor5.ndim)
rand_tensor5

torch.Size([1, 1, 1, 1, 1, 1, 1])
7
tensor([[[[[[[0.5188]]]]]]])
torch.Size([1, 2, 3, 4])
4
tensor([[[[0.6269, 0.4484, 0.5826, 0.6117],
          [0.3178, 0.4472, 0.2039, 0.6875],
          [0.8446, 0.9531, 0.8224, 0.9059]],

         [[0.6106, 0.8667, 0.9757, 0.6875],
          [0.8064, 0.8377, 0.4819, 0.4825],
          [0.9082, 0.6708, 0.6201, 0.8530]]]])
torch.Size([2, 3, 4, 5])
4
tensor([[[[0.5575, 0.9529, 0.2234, 0.3563, 0.5954],
          [0.2115, 0.4942, 0.6589, 0.8078, 0.3033],
          [0.5708, 0.7504, 0.2520, 0.4633, 0.1893],
          [0.9417, 0.2205, 0.7652, 0.2782, 0.8032]],

         [[0.2377, 0.7451, 0.1328, 0.0227, 0.0171],
          [0.1566, 0.3205, 0.2146, 0.3037, 0.9497],
          [0.1152, 0.7602, 0.8752, 0.4706, 0.1899],
          [0.3528, 0.6536, 0.9308, 0.3664, 0.9518]],

         [[0.0359, 0.6344, 0.2266, 0.0349, 0.5322],
          [0.0184, 0.7857, 0.3348, 0.6502, 0.4808],
          [0.3187, 0.9807, 0.4216, 0.2716, 0.7419],
          [0.1554, 0.6811, 0.5140, 0

tensor([[[[[0.8745, 0.8770, 0.6045, 0.1444, 0.7156, 0.6268],
           [0.7788, 0.5175, 0.0255, 0.7516, 0.7500, 0.1805]],

          [[0.9145, 0.6233, 0.1070, 0.9765, 0.2378, 0.7423],
           [0.5037, 0.2758, 0.5507, 0.9608, 0.8330, 0.6542]],

          [[0.9556, 0.6372, 0.2008, 0.1551, 0.5717, 0.9866],
           [0.8931, 0.0518, 0.7530, 0.0441, 0.5760, 0.2373]]],


         [[[0.3412, 0.6924, 0.9518, 0.2483, 0.3633, 0.0855],
           [0.3507, 0.8309, 0.0543, 0.5314, 0.8043, 0.5549]],

          [[0.1118, 0.9586, 0.4839, 0.7888, 0.7979, 0.6231],
           [0.2755, 0.5227, 0.8710, 0.1745, 0.5681, 0.3509]],

          [[0.5490, 0.0035, 0.4256, 0.7587, 0.4767, 0.8235],
           [0.0691, 0.7126, 0.7691, 0.5920, 0.3645, 0.7616]]]],



        [[[[0.8110, 0.8827, 0.9821, 0.4095, 0.0223, 0.1675],
           [0.6778, 0.9842, 0.6207, 0.2594, 0.2563, 0.0460]],

          [[0.6724, 0.1171, 0.5635, 0.4953, 0.1805, 0.3305],
           [0.2227, 0.8815, 0.3029, 0.8449, 0.9551, 0.0593]],

  

###Zeros and ones

In [34]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
ones.dtype

torch.float32

In [38]:
ones*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [39]:
# Use torch.range()
one_to_ten = torch.arange(0,1000,78)
one_to_ten

tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])

In [40]:
# Tensor like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
two_to_ten_like = torch.ones_like(input=one_to_ten)
two_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Data Type

**Note:** Tensor data types is one of the 3 big errors you may run into with PyTorch & deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

  Learn more about precision incomputing here:
  https://en.wikipedia.org/wiki/Precision_(computer_science)

In [42]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what datatype is the tensor(e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [48]:
int_long_tensor = torch.tensor([3,6,9], dtype= torch.long)
int_long_tensor

tensor([3, 6, 9])

In [49]:
float_32_tensor * int_long_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

  1. Tensors not right datatype - to do get datatype from a tensor,can use `tensor.type`
  2. Tensors not right shape - to get shape from a tensor use `tensor.shape`
  3. Tensors not on the right device - to get device from tensor use `tensor.device`

In [50]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5788, 0.2916, 0.3724, 0.0633],
        [0.8237, 0.5423, 0.1658, 0.1246],
        [0.2401, 0.7248, 0.4545, 0.6013]])

In [57]:
# Find details of Tensor

print(some_tensor)
print("Datatype of tensor: "+str(some_tensor.dtype))
print(f"Shape of tensor {some_tensor.shape}")
print(f"Device tensor is {some_tensor.device}")

tensor([[0.5788, 0.2916, 0.3724, 0.0633],
        [0.8237, 0.5423, 0.1658, 0.1246],
        [0.2401, 0.7248, 0.4545, 0.6013]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu


In [60]:
# Practice
some_tensor2 = torch.rand(3,4)
print(some_tensor2)
print("Datatype of tensor: "+str(some_tensor2.dtype))
print(f"Shape of tensor {some_tensor2.shape}")
print(f"Device tensor is {some_tensor2.device}")

some_tensor3 = torch.rand(3,4)
print(some_tensor3)
print("Datatype of tensor: "+str(some_tensor3.dtype))
print(f"Shape of tensor {some_tensor3.shape}")
print(f"Device tensor is {some_tensor3.device}")

tensor([[0.2530, 0.2544, 0.4412, 0.2370],
        [0.3701, 0.1592, 0.9790, 0.2702],
        [0.1590, 0.6578, 0.8616, 0.2661]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu
tensor([[1.1154e-01, 4.0451e-01, 6.9840e-01, 4.2934e-01],
        [1.0073e-04, 6.1621e-01, 1.2777e-01, 2.4715e-02],
        [6.7857e-01, 5.9901e-01, 6.9193e-01, 3.3782e-01]])
Datatype of tensor: torch.float32
Shape of tensor torch.Size([3, 4])
Device tensor is cpu


### Manipulating tensors (tensor operations)

Tensor operations include
* Addition
* Substraction
* Multiplications (elementwise)
* Division
* Matrix multiplication

In [61]:
# Create a tensor
tensor = torch.tensor([1,2,3])

#addition
tensor+10

tensor([11, 12, 13])

In [62]:
#multiply (elementwise)
tensor*10

tensor([10, 20, 30])

In [63]:
#Try out PyTorch in-built funstions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [64]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [65]:
tensor%3

tensor([1, 2, 0])

## Matrix Multiplication

Two main ways of performing multiplication in DL:

1. Elementwise
2. Matrix Multiplication (dot product)
In PyTorch we use `torch.matmul(tensor_1,tensor_2)`

Here can be found more: https://www.mathisfun.com/algebra/matrix-multiplying.html

In [68]:
# Element wise Multiplication
print(tensor,"*",tensor)
print("Equals",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [71]:
# Matrix Multiplication

print(tensor,".",tensor)
print("Equals ",torch.matmul(tensor,tensor))

tensor([1, 2, 3]) . tensor([1, 2, 3])
Equals  tensor(14)


In [74]:
# Matrix Multiplication by hand

1*1 + 2*2 + 3*3

14

In [75]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.21 ms, sys: 933 µs, total: 3.15 ms
Wall time: 3.12 ms


In [78]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 91 µs, sys: 5 µs, total: 96 µs
Wall time: 101 µs


tensor(14)